// content/puppies-static.ts
// Catálogo estático — By Império Dog
// Para atualizar disponibilidade: status → "available" | "reserved" | "sold"
// Hierarquia de preços: Fêmeas R$ 8.500 (todas as cores) | Machos R$ 7.500 (Creme, Preto) e R$ 6.500 (Cinza-Lobo, Laranja)

export const staticPuppies = [
  // ─── SPITZ CREME FÊMEA ──────────────────────────────────────────────────────
  {
    id: "spitz-creme-femea-01",
    name: "Spitz Creme Fêmea",
    slug: "spitz-alemao-anao-creme-femea",
    title: "Spitz Alemão Anão (Lulu da Pomerânia) Creme Fêmea | By Império Dog",
    color: "creme",
    cor: "Creme",
    sex: "female",
    gender: "female",
    status: "available",
    breed: "Spitz Alemão Anão (Lulu da Pomerânia)",
    size: "mini",
    city: "braganca-paulista",
    state: "SP",
    images: [
      "/filhotes/creme/creme-femea-01.jpg",
      "/filhotes/creme/creme-filhote-flores-05.jpg",
      "/filhotes/creme/creme-filhote-jardim-04.jpg",
      "/filhotes/creme/creme-filhote-flores-04.jpg",
      "/filhotes/creme/creme-filhote-jardim-03.jpg",
      "/filhotes/creme/creme-femea-02.jpg",
      "/filhotes/creme/creme-femea-03.jpg",
      "/filhotes/creme/creme-filhote-flores-01.jpg",
      "/filhotes/creme/creme-femea-flores-03.jpg",
      "/filhotes/creme/creme-femea-flores-04.jpg",
      "/filhotes/videos/spitz-creme.mp4",
      "/filhotes/videos/ninhada-creme-01.mp4",
    ],
    // Fêmea Creme — preço único de fêmea → R$ 8.500
    price_cents: 850000,
    priceCents: 850000,
    currency: "BRL",
    description:
      "Fêmea Creme de pelagem sedosa e temperamento dócil. Topo da hierarquia em valor e demanda. Socializada desde o nascimento em ambiente familiar. Registro oficial, protocolo vacinal em dia conforme a idade e mentoria vitalícia inclusa.",
    birth_date: "2024-08-01",
    nascimento: "2024-08-01",
    availableForShipping: true,
    hasPedigree: true,
    vaccinationStatus: "up-to-date",
    hasMicrochip: false,
    isHighlighted: true,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: false,
    reviewCount: 0,
    averageRating: 5,
    viewCount: 0,
    favoriteCount: 0,
    shareCount: 0,
    inquiryCount: 0,
    seoKeywords: [
      "spitz alemão creme fêmea",
      "lulu pomerânia creme femea sp",
      "filhote spitz creme bragança paulista",
      "spitz anão creme disponível",
    ],
  },

  // ─── SPITZ PRETO FÊMEA ──────────────────────────────────────────────────────
  {
    id: "spitz-preto-femea-01",
    name: "Spitz Preto Fêmea",
    slug: "spitz-alemao-anao-preto-femea",
    title: "Spitz Alemão Anão (Lulu da Pomerânia) Preto Fêmea | By Império Dog",
    color: "preto",
    cor: "Preto",
    sex: "female",
    gender: "female",
    status: "available",
    breed: "Spitz Alemão Anão (Lulu da Pomerânia)",
    size: "mini",
    city: "braganca-paulista",
    state: "SP",
    images: [
      "/filhotes/preto/preto-filhote-flores-01.jpg",
      "/filhotes/preto/preto-filhote-jardim-01.jpg",
      "/filhotes/preto/preto-filhote-flores-04.jpg",
      "/filhotes/preto/preto-filhote-jardim-04.jpg",
      "/filhotes/preto/preto-filhote-flores-05.jpg",
      "/filhotes/preto/preto-filhote-jardim-03.jpg",
      "/filhotes/preto/preto-filhote-2024-jardim-01.jpg",
      "/filhotes/preto/preto-filhote-2024-jardim-02.jpg",
      "/filhotes/videos/spitz-anao.mp4",
    ],
    // Fêmea Preta — preço único de fêmea → R$ 8.500
    price_cents: 850000,
    priceCents: 850000,
    currency: "BRL",
    description:
      "Fêmea Preta de pelagem brilhante e estrutura compacta. Disponibilidade limitada — ninhadas esporádicas. Criada com socialização guiada, laudos de saúde e registro oficial.",
    birth_date: "2024-08-01",
    nascimento: "2024-08-01",
    availableForShipping: true,
    hasPedigree: true,
    vaccinationStatus: "up-to-date",
    hasMicrochip: false,
    isHighlighted: true,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: false,
    reviewCount: 0,
    averageRating: 5,
    viewCount: 0,
    favoriteCount: 0,
    shareCount: 0,
    inquiryCount: 0,
    seoKeywords: [
      "spitz alemão preto fêmea",
      "lulu pomerânia preto femea sp",
      "spitz anão preto fêmea bragança paulista",
      "filhote spitz preto fêmea disponível",
    ],
  },

  // ─── SPITZ LARANJA FÊMEA ────────────────────────────────────────────────────
  {
    id: "spitz-laranja-femea-01",
    name: "Spitz Laranja Fêmea",
    slug: "spitz-alemao-anao-laranja-femea",
    title: "Spitz Alemão Anão (Lulu da Pomerânia) Laranja Fêmea | By Império Dog",
    color: "laranja",
    cor: "Laranja",
    sex: "female",
    gender: "female",
    status: "available",
    breed: "Spitz Alemão Anão (Lulu da Pomerânia)",
    size: "mini",
    city: "braganca-paulista",
    state: "SP",
    images: [
      "/filhotes/laranja/laranja-femea-flores-01.jpg",
      "/filhotes/laranja/laranja-femea-jardim-03.jpg",
      "/filhotes/laranja/laranja-femea-brinquedos-04.jpg",
      "/filhotes/laranja/laranja-femea-flores-02.jpg",
      "/filhotes/laranja/laranja-femea-jardim-02.jpg",
      "/filhotes/laranja/laranja-femea-brinquedos-03.jpg",
      "/filhotes/laranja/laranja-femea-interior-01.jpg",
      "/filhotes/laranja/laranja-femea-01.jpg",
      "/filhotes/laranja/laranja-femea-brinquedos-01.jpg",
      "/filhotes/laranja/laranja-femea-brinquedos-02.jpg",
      "/filhotes/videos/laranja-femea-jardim.mp4",
      "/filhotes/videos/ninhada-jun22-01.mp4",
    ],
    // Fêmea Laranja — preço único de fêmea → R$ 8.500
    price_cents: 850000,
    priceCents: 850000,
    currency: "BRL",
    description:
      "Fêmea Laranja de coloração vibrante, exatamente dentro do padrão FCI. Temperamento alegre e extremamente carinhosa. Criada com socialização guiada e acompanhamento veterinário completo.",
    birth_date: "2024-08-01",
    nascimento: "2024-08-01",
    availableForShipping: true,
    hasPedigree: true,
    vaccinationStatus: "up-to-date",
    hasMicrochip: false,
    isHighlighted: true,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false,
    reviewCount: 0,
    averageRating: 5,
    viewCount: 0,
    favoriteCount: 0,
    shareCount: 0,
    inquiryCount: 0,
    seoKeywords: [
      "spitz alemão laranja fêmea",
      "lulu pomerânia laranja femea sp",
      "filhote spitz laranja disponível",
      "spitz anão laranja fêmea",
    ],
  },

  // ─── SPITZ CREME MACHO ──────────────────────────────────────────────────────
  {
    id: "spitz-creme-macho-01",
    name: "Spitz Creme Macho",
    slug: "spitz-alemao-anao-creme-macho",
    title: "Spitz Alemão Anão (Lulu da Pomerânia) Creme Macho | By Império Dog",
    color: "creme",
    cor: "Creme",
    sex: "male",
    gender: "male",
    status: "available",
    breed: "Spitz Alemão Anão (Lulu da Pomerânia)",
    size: "mini",
    city: "braganca-paulista",
    state: "SP",
    images: [
      "/filhotes/creme/creme-macho-01.jpg",
      "/filhotes/creme/creme-filhote-flores-06.jpg",
      "/filhotes/creme/creme-filhote-jardim-01.jpg",
      "/filhotes/creme/creme-filhote-folha-01.jpg",
      "/filhotes/creme/creme-filhote-flores-02.jpg",
      "/filhotes/creme/creme-filhote-jardim-05.jpg",
      "/filhotes/creme/creme-macho-02.jpg",
      "/filhotes/creme/creme-macho-flores-01.jpg",
      "/filhotes/creme/creme-filhote-jardim-02.jpg",
      "/filhotes/videos/spitz-branco.mp4",
      "/filhotes/videos/creme-dupla.mp4",
    ],
    // Macho Creme — faixa alta de macho (Creme/Preto) → R$ 7.500
    price_cents: 750000,
    priceCents: 750000,
    currency: "BRL",
    description:
      "Macho Creme com estrutura compacta dentro do padrão FCI nº 97 (altura na cernelha de 21 cm ± 3 cm). Criado com socialização guiada, alimentação premium e acompanhamento veterinário. Registro oficial.",
    birth_date: "2024-08-01",
    nascimento: "2024-08-01",
    availableForShipping: true,
    hasPedigree: true,
    vaccinationStatus: "up-to-date",
    hasMicrochip: false,
    isHighlighted: false,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    reviewCount: 0,
    averageRating: 5,
    viewCount: 0,
    favoriteCount: 0,
    shareCount: 0,
    inquiryCount: 0,
    seoKeywords: [
      "spitz alemão creme macho",
      "lulu pomerânia macho creme sp",
      "spitz anão macho bragança paulista",
      "filhote spitz macho disponível",
    ],
  },

  // ─── SPITZ PRETO MACHO ──────────────────────────────────────────────────────
  {
    id: "spitz-preto-macho-01",
    name: "Spitz Preto Macho",
    slug: "spitz-alemao-anao-preto-macho",
    title: "Spitz Alemão Anão (Lulu da Pomerânia) Preto Macho | By Império Dog",
    color: "preto",
    cor: "Preto",
    sex: "male",
    gender: "male",
    status: "available",
    breed: "Spitz Alemão Anão (Lulu da Pomerânia)",
    size: "mini",
    city: "braganca-paulista",
    state: "SP",
    images: [
      "/filhotes/preto/preto-01.jpg",
      "/filhotes/preto/preto-filhote-jardim-01.jpg",
      "/filhotes/preto/preto-filhote-flores-01.jpg",
      "/filhotes/preto/preto-filhote-jardim-03.jpg",
      "/filhotes/preto/preto-filhote-flores-08.jpg",
      "/filhotes/preto/preto-filhote-flores-07.jpg",
      "/filhotes/preto/preto-filhote-2025-jardim-01.jpg",
      "/filhotes/preto/preto-filhote-jardim-02.jpg",
      "/filhotes/videos/spitz-anao.mp4",
    ],
    // Macho Preto — faixa alta de macho (Creme/Preto) → R$ 7.500
    price_cents: 750000,
    priceCents: 750000,
    currency: "BRL",
    description:
      "Macho Preto de pelagem brilhante e estrutura compacta. Cor menos comum e bastante procurada. Consulte a agenda de visitas.",
    birth_date: "2025-04-01",
    nascimento: "2025-04-01",
    availableForShipping: true,
    hasPedigree: true,
    vaccinationStatus: "up-to-date",
    hasMicrochip: false,
    isHighlighted: false,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    reviewCount: 0,
    averageRating: 5,
    viewCount: 0,
    favoriteCount: 0,
    shareCount: 0,
    inquiryCount: 0,
    seoKeywords: [
      "spitz alemão preto macho",
      "lulu pomerânia preto macho sp",
      "spitz anão preto bragança paulista",
      "filhote spitz preto disponível",
    ],
  },

  // ─── SPITZ LARANJA MACHO ────────────────────────────────────────────────────
  {
    id: "spitz-laranja-macho-01",
    name: "Spitz Laranja Macho",
    slug: "spitz-alemao-anao-laranja-macho",
    title: "Spitz Alemão Anão (Lulu da Pomerânia) Laranja Macho | By Império Dog",
    color: "laranja",
    cor: "Laranja",
    sex: "male",
    gender: "male",
    status: "available",
    breed: "Spitz Alemão Anão (Lulu da Pomerânia)",
    size: "mini",
    city: "braganca-paulista",
    state: "SP",
    images: [
      "/filhotes/laranja/laranja-macho-flores-01.jpg",
      "/filhotes/laranja/laranja-macho-flores-02.jpg",
      "/filhotes/laranja/laranja-macho-01.jpg",
      "/filhotes/laranja/laranja-macho-jardim-01.jpg",
      "/filhotes/laranja/laranja-macho-02.jpg",
      "/filhotes/laranja/laranja-macho-flores-03.jpg",
      "/filhotes/laranja/laranja-macho-flores-04.jpg",
      "/filhotes/videos/spitz-laranja-macho.mp4",
      "/filhotes/videos/laranja-macho-jardim.mp4",
      "/filhotes/videos/ninhada-laranja-01.mp4",
    ],
    // Macho Laranja — faixa baixa de macho (Cinza-Lobo/Laranja) → R$ 6.500
    price_cents: 650000,
    priceCents: 650000,
    currency: "BRL",
    description:
      "Macho Laranja com expressão marcante e pelagem densa. Criado com acompanhamento veterinário e laudo de saúde. Registro oficial incluso, com emissão e entrega conforme o prazo da entidade responsável e as condições previstas em contrato.",
    birth_date: "2024-08-01",
    nascimento: "2024-08-01",
    availableForShipping: true,
    hasPedigree: true,
    vaccinationStatus: "up-to-date",
    hasMicrochip: false,
    isHighlighted: false,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    reviewCount: 0,
    averageRating: 5,
    viewCount: 0,
    favoriteCount: 0,
    shareCount: 0,
    inquiryCount: 0,
    seoKeywords: [
      "spitz alemão laranja macho",
      "lulu pomerânia macho laranja",
      "spitz laranja macho bragança paulista",
      "filhote spitz laranja macho disponível",
    ],
  },

  // ─── SPITZ WOLF SABLE FÊMEA ─────────────────────────────────────────────────
  {
    id: "spitz-wolf-sable-femea-01",
    name: "Spitz Cinza-Lobo (Wolf Sable) Fêmea",
    slug: "spitz-alemao-anao-wolf-sable-femea",
    title: "Spitz Alemão Anão (Lulu da Pomerânia) Cinza-Lobo (Wolf Sable) Fêmea | By Império Dog",
    color: "wolf-sable",
    cor: "Cinza-Lobo",
    sex: "female",
    gender: "female",
    status: "available",
    breed: "Spitz Alemão Anão (Lulu da Pomerânia)",
    size: "mini",
    city: "braganca-paulista",
    state: "SP",
    images: [
      "/filhotes/wolf-sable/wolf-sable-femea-01.jpg",
      "/filhotes/wolf-sable/wolf-sable-femea-abeto-01.jpg",
      "/filhotes/wolf-sable/wolf-sable-filhote-flores-01.jpg",
      "/filhotes/wolf-sable/wolf-sable-filhote-flores-03.jpg",
      "/filhotes/wolf-sable/wolf-sable-femea-abeto-02.jpg",
      "/filhotes/wolf-sable/wolf-sable-femea-abeto-03.jpg",
      "/filhotes/wolf-sable/wolf-sable-femea-jardim-01.jpg",
      "/filhotes/wolf-sable/wolf-sable-femea-02.jpg",
      "/filhotes/wolf-sable/wolf-sable-filhote-brinquedos-01.jpg",
      "/filhotes/videos/wolf-sable-jardim.mp4",
    ],
    // Cinza-Lobo Fêmea — preço único de fêmea → R$ 8.500
    price_cents: 850000,
    priceCents: 850000,
    currency: "BRL",
    description:
      "Fêmea Cinza-Lobo (Wolf Sable) — coloração bicolor com máscara cinza sobre base laranja, reconhecida pela FCI. Disponibilidade limitada, consulte agenda.",
    birth_date: "2024-08-01",
    nascimento: "2024-08-01",
    availableForShipping: true,
    hasPedigree: true,
    vaccinationStatus: "up-to-date",
    hasMicrochip: false,
    isHighlighted: true,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: false,
    reviewCount: 0,
    averageRating: 5,
    viewCount: 0,
    favoriteCount: 0,
    shareCount: 0,
    inquiryCount: 0,
    seoKeywords: [
      "spitz alemão wolf sable fêmea",
      "lulu pomerânia wolf sable sp",
      "spitz sable cinza laranja femea",
      "filhote spitz wolf sable disponível",
    ],
  },

  // ─── SPITZ WOLF SABLE MACHO ─────────────────────────────────────────────────
  {
    id: "spitz-wolf-sable-macho-01",
    name: "Spitz Cinza-Lobo (Wolf Sable) Macho",
    slug: "spitz-alemao-anao-wolf-sable-macho",
    title: "Spitz Alemão Anão (Lulu da Pomerânia) Cinza-Lobo (Wolf Sable) Macho | By Império Dog",
    color: "wolf-sable",
    cor: "Cinza-Lobo",
    sex: "male",
    gender: "male",
    status: "available",
    breed: "Spitz Alemão Anão (Lulu da Pomerânia)",
    size: "mini",
    city: "braganca-paulista",
    state: "SP",
    images: [
      "/filhotes/wolf-sable/wolf-sable-filhote-jardim-04.jpg",
      "/filhotes/wolf-sable/wolf-sable-filhote-flores-02.jpg",
      "/filhotes/wolf-sable/wolf-sable-filhote-jardim-02.jpg",
      "/filhotes/wolf-sable/wolf-sable-macho-abeto-01.jpg",
      "/filhotes/wolf-sable/wolf-sable-macho-abeto-02.jpg",
      "/filhotes/wolf-sable/wolf-sable-filhote-jardim-01.jpg",
      "/filhotes/wolf-sable/wolf-sable-filhote-jardim-03.jpg",
      "/filhotes/wolf-sable/wolf-sable-macho-01.jpg",
      "/filhotes/videos/wolf-sable-jardim.mp4",
      "/filhotes/videos/spitz-anao.mp4",
    ],
    // Cinza-Lobo Macho — faixa baixa de macho (Cinza-Lobo/Laranja) → R$ 6.500
    price_cents: 650000,
    priceCents: 650000,
    currency: "BRL",
    description:
      "Macho Cinza-Lobo (Wolf Sable) com porte elegante e pelagem exuberante. Coloração bicolor cinza e laranja — padrão reconhecido pela FCI.",
    birth_date: "2024-08-01",
    nascimento: "2024-08-01",
    availableForShipping: true,
    hasPedigree: true,
    vaccinationStatus: "up-to-date",
    hasMicrochip: false,
    isHighlighted: false,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false,
    reviewCount: 0,
    averageRating: 5,
    viewCount: 0,
    favoriteCount: 0,
    shareCount: 0,
    inquiryCount: 0,
    seoKeywords: [
      "spitz alemão wolf sable macho",
      "lulu pomerânia sable macho sp",
      "spitz bicolor cinza laranja macho",
      "filhote spitz sable disponível",
    ],
  },
];
