// AUTO-GENERATED by scripts/gen-client-photos.mjs
export type ClientPhoto = { src: string; width: number; height: number };
const CLIENT_PHOTOS: readonly ClientPhoto[] = [
  {
    "src": "/clientes/ana-paula-jundiai.jpeg",
    "width": 980,
    "height": 1600
  },
  {
    "src": "/clientes/ana.jpeg",
    "width": 900,
    "height": 1125
  },
  {
    "src": "/clientes/bruno-familia-jundiai.jpeg",
    "width": 719,
    "height": 1363
  },
  {
    "src": "/clientes/bruno.jpeg",
    "width": 1020,
    "height": 1007
  },
  {
    "src": "/clientes/camila.jpeg",
    "width": 1020,
    "height": 1213
  },
  {
    "src": "/clientes/cliente1-byimperiodog.jpeg",
    "width": 1272,
    "height": 1280
  },
  {
    "src": "/clientes/cliente10-byimperiodog.jpeg",
    "width": 1002,
    "height": 679
  },
  {
    "src": "/clientes/cliente12-byimperiodog.jpeg",
    "width": 951,
    "height": 1120
  },
  {
    "src": "/clientes/cliente14-byimperiodog.jpeg",
    "width": 1020,
    "height": 756
  },
  {
    "src": "/clientes/cliente16-byimperiodog.jpeg",
    "width": 1020,
    "height": 1156
  },
  {
    "src": "/clientes/cliente17-byimperiodog.jpeg",
    "width": 1020,
    "height": 1008
  },
  {
    "src": "/clientes/cliente18-byimperiodog.jpeg",
    "width": 1020,
    "height": 1251
  },
  {
    "src": "/clientes/cliente20-byimperiodog.jpeg",
    "width": 1020,
    "height": 1228
  },
  {
    "src": "/clientes/cliente21-byimperiodog.jpeg",
    "width": 1020,
    "height": 1244
  },
  {
    "src": "/clientes/cliente22-byimperiodog.jpeg",
    "width": 1020,
    "height": 973
  },
  {
    "src": "/clientes/cliente23-byimperiodog.jpeg",
    "width": 1020,
    "height": 996
  },
  {
    "src": "/clientes/cliente24-byimperiodog.jpeg",
    "width": 1020,
    "height": 995
  },
  {
    "src": "/clientes/cliente25-byimperiodog.jpeg",
    "width": 1020,
    "height": 1228
  },
  {
    "src": "/clientes/cliente27-byimperiodog.jpeg",
    "width": 1020,
    "height": 991
  },
  {
    "src": "/clientes/cliente3-byimperiodog.jpeg",
    "width": 803,
    "height": 780
  },
  {
    "src": "/clientes/cliente30-byimperiodog.jpeg",
    "width": 1020,
    "height": 872
  },
  {
    "src": "/clientes/cliente31-byimperiodog.jpeg",
    "width": 1020,
    "height": 989
  },
  {
    "src": "/clientes/cliente32-byimperiodog.jpeg",
    "width": 960,
    "height": 960
  },
  {
    "src": "/clientes/cliente4-byimperiodog.jpeg",
    "width": 1080,
    "height": 1080
  },
  {
    "src": "/clientes/cliente5-byimperiodog.jpeg",
    "width": 1600,
    "height": 1200
  },
  {
    "src": "/clientes/cliente8-byimperiodog.jpeg",
    "width": 1020,
    "height": 991
  },
  {
    "src": "/clientes/cliente9-byimperiodog.jpeg",
    "width": 1020,
    "height": 1002
  },
  {
    "src": "/clientes/fernanda.jpeg",
    "width": 1020,
    "height": 989
  },
  {
    "src": "/clientes/joao.jpeg",
    "width": 1020,
    "height": 1226
  },
  {
    "src": "/clientes/livia.jpeg",
    "width": 1020,
    "height": 1002
  },
  {
    "src": "/clientes/lucas.jpeg",
    "width": 1020,
    "height": 1209
  },
  {
    "src": "/clientes/marina.jpeg",
    "width": 900,
    "height": 1600
  },
  {
    "src": "/clientes/patricia.jpeg",
    "width": 1020,
    "height": 1244
  },
  {
    "src": "/clientes/paula.jpeg",
    "width": 1128,
    "height": 1128
  },
  {
    "src": "/clientes/ricardo.jpeg",
    "width": 1020,
    "height": 558
  },
  {
    "src": "/clientes/roberto.jpeg",
    "width": 1020,
    "height": 972
  },
  {
    "src": "/clientes/ronaldo-braganca-paulista.jpeg",
    "width": 960,
    "height": 1280
  }
];
export default CLIENT_PHOTOS;
