-- Supabase table for lead funnel (compatível com o endpoint Next.js)
-- Adapta campos para rastrear contexto (UTM, página, dispositivo) e LGPD
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  -- dados do contato
  nome text not null,
  telefone text not null, -- E.164 sem formatação
  cidade text,
  estado text,
  sexo_preferido text check (sexo_preferido in ('macho','femea','tanto_faz')),
  cor_preferida text,
  prazo_aquisicao text check (prazo_aquisicao in ('imediato','1_mes','2_3_meses','3_mais')),
  mensagem text,
  consent_lgpd boolean default false,
  consent_version text default '1.0',
  consent_timestamp timestamptz default now(),
  -- contexto da página / navegação
  page text,          -- pathname
  page_type text,     -- catalog / detail / color / city / intent / blog
  page_slug text,
  page_color text,
  page_city text,
  page_intent text,
  referer text,
  gclid text,
  fbclid text,
  ip_address text,
  user_agent text,
  -- UTMs
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  source text default 'site_org',
  -- status do pipeline
  status text default 'novo'
);

-- Índices
create index if not exists leads_phone_created_idx on public.leads (telefone, created_at desc);
create index if not exists idx_leads_status on public.leads(status);
create index if not exists idx_leads_created_at on public.leads(created_at desc);
